[package]
name = "gmanim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.20.1"
nalgebra = "*"
rusttype = "*"
usvg = "0.36.0"
tiny-skia = "*"
fern = "*"
log = "*"
humantime = "*"
